config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers, :favourites
    end
  end
resources :microposts do
    member do
      get :favouritedby
    end 
    
  end

  resources :sessions,      only: [:new, :create, :destroy]
  
  resources :relationships, only: [:create, :destroy]
  resources :favrelationships, only: [:create, :destroy]
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  get "static_pages/home"

  get "static_pages/help"
  
  get "static_pages/about"

  get "static_pages/contact"

   root :to => 'static_pages#home'

end

app/views/shared/_error_mess.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_fav.html.erb
<%= form_for(feed_item.favrelationships.build(favby_id: feed_item.user.id), remote: true, favmp_id: feed_item.id) do |f| %>
        <div><%= f.hidden_field :favmp_id %></div>
    <%= f.submit "Like", class: "btn btn-small btn-success" %>
    <% end %>

app/views/shared/_fav_form.html.erb
<% if feed_item.favouritedby?(current_user) %>
    <%= render 'shared/unfav' , :feed_item => feed_item %>
<% else %>
    <%= render 'shared/fav' , :feed_item => feed_item %>
<% end %>


<span class="timestamp">
<% array=Array.new %>

<% if feed_item.favby_users.count ==0 %>
  Be the first one to Like this!!!

<% elsif feed_item.favby_users.count ==1 %>
  <% if feed_item.favouritedby?(current_user) %>
    <%=  "You "  %>like this.
  <% else %>
    <%=  feed_item.favby_users.first.name %> likes this
  <% end %>

<% elsif feed_item.favby_users.count==2 %>
  <% feed_item.favby_users.each do |user| %>
    <% array.push(user.name) %>
    
  <% end %>
  <% if feed_item.favouritedby?(current_user)%>
        <%=  "You " %>and
        <% array.delete(current_user.name) %>
        <%= array.first %> likes this
  <% else %>
       <%= array.first %> <%=" and "%> <%=array.last%> likes this
  <% end %>    

<% elsif feed_item.favby_users.count>2 %>
  <% feed_item.favby_users.each do |user| %>
    <% array.push(user.name) %>
    
  <% end %>
  <% if feed_item.favouritedby?(current_user)%>
        <%=  "You, " %>
        <% array.delete(current_user.name)%>
        <%= array.first %><%=" and "%> <%=array.count-1 %> other<% if array.count > 2 %>'s<%end%>
        likes this

  <% else %>
        <%= array.first %>,<%=array.second %> <%=" and "%> <%=array.count-2 %>other<% if array.count>3 %><%= "'s "%><% end %>
        likes this.
  <% end %>
<% end %>

</span>

app/views/shared/_feed.html.erb
<div id="myfeed">
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>
</div>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <% @post = feed_item %>
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
  
    
  
  <div id="M<%= feed_item.id %>" >
    <%= render "shared/fav_form" , :feed_item => feed_item  %>
  </div>

</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_mess', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
  <a  href="<%= favourites_user_path(@user) %>">
  <strong id="nooffavs"  class="stat">
  <%= @user.favourites.count %>
</strong> Liked Posts
</a>
  

</div>

app/views/shared/_unfav.html.erb
<%= form_for(feed_item.favrelationships.find_by_favby_id(current_user), remote: true, user: current_user, 
             html: { method: :delete }) do |f| %>
    <%= f.submit "Unlike", class: "btn btn-small btn-danger" %>
    <% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>